services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver
        volumes:
            - .:/code
        ports:
            - "8000"
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
            - EXCHANGE_BASE_URL=${EXCHANGE_BASE_URL}
