services:
    api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ".:/code"
        ports:
            - "8000:8000"
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
            - EXCHANGE_BASE_URL=${EXCHANGE_BASE_URL}
