services:
    api:
        build: .
        command: python manage.py runserver
        volumes:
            - .:/code
            - db.sqlite3:/db.sqlite3
        ports:
            - "8002:8000"
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
            - EXCHANGE_BASE_URL=${EXCHANGE_BASE_URL}
