# Generated by Django 5.1 on 2024-08-12 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency_from", models.CharField(max_length=3)),
                ("currency_to", models.CharField(max_length=3)),
                ("amount", models.IntegerField()),
                ("conversion_rate", models.CharField(editable=False, max_length=255)),
                ("converted_amount", models.IntegerField(editable=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
